config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resource :bulk_uploads, only: [:show, :create]
  devise_for :users
  root to: "home#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  CSV_FILE_HEADERS = %w[record_id email first_name last_name phone_number status error].freeze

  belongs_to :user

  validates :first_name, presence: true, uniqueness: {scope: [:last_name, :user_id] }
  validates :last_name, presence: true
  validates :phone_number, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }, uniqueness: {scope: :user_id}

  def self.create_csv_record!(csv_row, user_id)
    create! csv_row.to_hash.except(*meta_csv_fields).merge(user_id: user_id)
  end

  def self.meta_csv_fields
    %w[record_id status error]
  end

  def as_csv_row
    [id, email, first_name, last_name, phone_number]
  end

  private_class_method :meta_csv_fields
end

app/models/csv_upload_report.rb
class CsvUploadReport < ApplicationRecord
  belongs_to :user
  has_one_attached :report

  def self.latest_upload_reports
    order(created_at: :desc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :contacts
  has_many :csv_upload_reports

  delegate :latest_upload_reports, to: :csv_upload_reports
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bulk_uploads_controller.rb
class BulkUploadsController < ApplicationController
  before_action :authenticate_user!
  before_action :validate_file, only: [:create]
  before_action :validate_csv_headers, only: [:create]

  def show
    @csv_upload_reports = current_user.latest_upload_reports
  end

  def create
    report = csv_importer.process
    if report.bad_data?
      redirect_to bulk_uploads_path, alert: 'Some of the records are not processed. Please see the report below for details, and re-upload the report post fixing the errors'
    else
      redirect_to contacts_path, notice: 'Successfully uploaded all the contacts, Please see the report in bulk uploads page for further details'
    end
  end

  private
    def csv_importer
      @csv_importer ||= ContactsCsvImporter.new(file, current_user)
    end

    def file
      params[:file]
    end

    def validate_csv_headers
      unless csv_importer.valid_headers?
        redirect_to bulk_uploads_path, notice: 'Please re-upload the csv file with valid headers'
        return
      end
    end

    def validate_file
      unless csv_importer.valid_file_extension?
        redirect_to bulk_uploads_path, notice: 'Only CSV files are allowed'
        return
      end

      if csv_importer.exceeds_max_file_size?
        redirect_to bulk_uploads_path, notice: "Max file size is #{ContactsCsvImporter::PRETTY_MAX_FILE_SIZE}"
        return
      end

      if csv_importer.exceeds_max_records?
        redirect_to bulk_uploads_path, notice: "Cannot process more than #{ContactsCsvImporter::MAX_RECORDS} records at once"
        return
      end
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = current_user.contacts.order(created_at: :desc)
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)
    @contact.user = current_user

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = current_user.contacts.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :email, :phone_number)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :check_logged_in_user

  def show
  end

  private
    def check_logged_in_user
      redirect_to contacts_path if current_user
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bulk_uploads/_reports.html.erb
<% if @csv_upload_reports.present? %>
  <h3> Reports </h3>
  <table class="table table-striped w-50">
    <tbody>
      <% @csv_upload_reports.each do |upload_report| %>
        <tr>
          <td><%= upload_report.created_at %></td>
          <td><%= link_to 'Download', rails_blob_path(upload_report.report, disposition: "attachment") %> </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/bulk_uploads/create.html.erb
<h1>BulkUploads#create</h1>
<p>Find me in app/views/bulk_uploads/create.html.erb</p>

app/views/bulk_uploads/show.html.erb
<%= form_tag(bulk_uploads_path, multipart: true) do |form| %>
  <div class="jumbotron">
    <h1 class="display-4">Bulk Upload</h1>
    <p class="lead">Upload a csv file with the following headers email, first_name, last_name, phone_number </p>
    <hr class="my-4">
    <p> A report will be generated post processing the CSV file.
    The status, error mesage are present for individual records.
    Fix the errors if applicable and reupload the same file again.
    record_id is present in the output file for verification purposes.
    Records with record_id will not be processed, as they are already present in the system.
    </p>
    <p><b>Note:</b> Do not upload a file with more than 100 records.</p>
    <p class="lead">
      <%= file_field_tag "file", required: true %>
      <br/>
      <br/>
      <%= submit_tag "Upload", class: "btn btn-light btn-lg border-black" %>
    </p>
  </div>
<% end %>

<%= render "reports" %>

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="w-50">
    <div class="form-group">
      <%= form.label :first_name %>
      <%= form.text_field :first_name, class: "form-control", required: true %>
    </div>

    <div class="form-group">
      <%= form.label :last_name %>
      <%= form.text_field :last_name, class: "form-control", required: true %>
    </div>

    <div class="form-group">
      <%= form.label :email %>
      <%= form.text_field :email, class: "form-control", required: true %>
    </div>

    <div class="form-group">
      <%= form.label :phone_number %>
      <%= form.text_field :phone_number, class: "form-control", required: true %>
    </div>
    <br/>
    <div class="actions">
    <%= form.submit("Submit", class: "btn btn-light border-black" ) %>
    </div>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<h1>Contacts</h1>

<%= link_to 'New Contact', new_contact_path, class: 'btn btn-light border-black' %>
<%= link_to 'Bulk Upload', bulk_uploads_path, class: 'btn btn-light border-black' %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.first_name %></td>
        <td><%= contact.last_name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.phone_number %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/contacts/new.html.erb
<h3>New Contact</h3>

<%= render 'form', contact: @contact %>

<br/>
<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-striped">
  <tbody>
    <tr>
      <td><strong>First Name</strong></td>
      <td><%= @contact.first_name %></td>
    </tr>
    <tr>
      <td><strong>Last Name</strong></td>
      <td><%= @contact.last_name %></td>
    </tr>
    <tr>
      <td><strong>Email</strong></td>
      <td><%= @contact.email %></td>
    </tr>
    <tr>
      <td><strong>Phone Number</strong></td>
      <td><%= @contact.phone_number %></td>
    </tr>
  </tbody>
</table>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/home/show.html.erb
<br>
<br>
<br>
<br>
<div class="jumbotron">
  <h1 class="display-4">Hello, world!</h1>
  <p class="lead">This is a simple application to manage your Contacts</p>
  <hr class="my-4">
  <p></p>
  <%= link_to 'Sign up', new_user_registration_path, class: "btn btn-light btn-lg border-black" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContactManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/nav" %>
    <% if notice %>
      <p class="alert alert-secondary"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <div class="set-layout-padding">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_nav.html.erb
<div class="navbar navbar-light bg-light">
  <b><div><%= link_to 'Home', root_url %></div></b>
  <b><div> <%= link_to 'Contact Manager', contacts_path %> </div></b>
  <% if current_user %>
    <b><%= link_to "Sign out", destroy_user_session_path, method: :delete %></b>
  <% else %>
    <b><%= link_to "Login", user_session_path %></b>
  <% end %>
</div>